### ISSUE TITLE
Step 43 doesn't work on Mac OS X Safari or Chrome browsers: submit button does not work

### ISSUE THREAD

**Issue by SmartLizard** [awslabs/aws-serverless-website-workshop#1]
I have copied the files for part 2 of the tutorial across according to the instructions:

`aws s3 sync work/ s3://<myname>-wildrydes`

However even after refreshing the browser lots of times and using both Safari and Chrome, when I click on 'SUBMIT' on the form, nothing happens.

**Comment by jpignata** [comment]
Hmm - can you see your debugger console provides any details? It's possible there's an issue either with the policy setup in a previous step or a mismatch in the DynamoDB table name or columns due to (for example) casing.

**Comment by rrjohnson** [comment]
Hi @jpignata 

Here are the error messages from Chrome:

`Typekit: the domain "rjohnson-wildrydes.s3-website-eu-west-1.amazonaws.com" isn't in the list of published domains for kit "dmq4txp".
T.load @ dmq4txp.js:38`

and:

`Failed to load resource: the server responded with a status of 400 (Bad Request)
index.js:26 Error: One or more parameter values were invalid: An AttributeValue may not contain an empty string
    at constructor.s (aws-sdk.min.js:34)
    at constructor.callListeners (aws-sdk.min.js:35)
    at constructor.emit (aws-sdk.min.js:35)
    at constructor.emitEvent (aws-sdk.min.js:35)
    at constructor.e (aws-sdk.min.js:34)
    at a.runTo (aws-sdk.min.js:36)
    at aws-sdk.min.js:36
    at constructor.<anonymous> (aws-sdk.min.js:34)
    at constructor.<anonymous> (aws-sdk.min.js:35)
    at constructor.callListeners (aws-sdk.min.js:35)`

Here is the error message in Safari:

`Typekit: the domain "rjohnson-wildrydes.s3-website-eu-west-1.amazonaws.com" isn't in the list of published domains for kit "dmq4txp".

load - dmq4txp.js:38:493
Fa - dmq4txp.js:40:183
load - dmq4txp.js:39:492
load -dmq4txp.js:40:623
Global code - index.html:15`

Let me know if there is any more information you would like me to provide.

**Comment by jpignata** [comment]
Here's what I see trying to submit the form on the bucket you've provided:

Error: User: arn:aws:sts::993665411887:assumed-role/Cognito_wildrydesUnauth_Role/CognitoIdentityCredentials is not authorized to perform: dynamodb:PutItem on resource: arn:aws:dynamodb:eu-west-1:993665411887:table/Wildrydes_Emails

Ensure that your Cognito unauth role has the ability to put item into the table as outlined in step 33. Happy to help further via email.

**Comment by rrjohnson** [comment]
@jpignata Thank you very much, that solved the issue!
