### ISSUE TITLE
Step 65 - lambda function trigger "invocation error"

### ISSUE THREAD

**Issue by suibinz** [awslabs/aws-serverless-website-workshop#2]
I am getting on the lambda function: Batch size: 1Last result: PROBLEM: Function call failed

I think without a Node "console", debugging gets tricky - will be nice to have some kind of console to help debug as a feature in AWS Lambda.

Regardless, any idea if the Node function having some problem, or somewhere else?

**Comment by jpignata** [comment]
Hi! Do you see any logs in CloudWatch Logs for your function with any
further details?

**Comment by suibinz** [comment]
Ahh... I was new to the CloudWatch and was not aware of the log. Here is the exception I have:
{
    "errorMessage": "Email address is not verified. The following identities failed the check in region US-WEST-2: suibinzh+1@gmail.com",
    "errorType": "MessageRejected",
    "stackTrace": [
        "Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/query.js:40:29)",
        "Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)",
        "Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)",
        "Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:668:14)",
        "Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "/var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:670:12)",
        "Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)"
    ]
}

Maybe some issue with my Conigto_UnAuth role?

**Comment by jpignata** [comment]
Gotcha. It's more likely that your email address is not verified via SES. If you go to the SES console and verify that email address, the function should succeed. You should be able to follow the first few steps of lab 2 to do this. After that, you may need to delete and recreate the trigger.

Hope that helps!
