### ISSUE TITLE
Problem with external font JS

### ISSUE THREAD

**Issue by rnzaws** [awslabs/aws-serverless-website-workshop#7]
We ran into several times is related to the code below. This library needs some sort of registration of source domains (cloudfront.net and/or the s3 static domain) or it fails for some (I hit two cases on Windows).

I do not have an Adobe account or I would patch myself.

```<script src="https://use.typekit.net/dmq4txp.js"></script>```
```<script>try{Typekit.load({ async: true });}catch(e){}</script>```

**Comment by jpignata** [comment]
I don't know where this came from actually. I'll do some sleuthing. The
error is bothersome though.
